---
# Installing Internet browser

- name: Checking Google Chrome installation
  sudo: yes
  register: inst_chrome
  file: path=/opt/google/chrome state=directory

- name: Installing Google Chrome dependencies
  sudo: yes
  apt: name=libgconf2-4,libxss1 state=latest
  when: inst_chrome.chnaged

- name: Downloading Google Chrome
  get_url: url=$chrome dest=/tmp/google-chrome-stable_current_amd64.deb
  when: inst_chrome.chnaged

- name: Installing Google Chrome
  sudo: yes
  shell: dpkg -i /tmp/google-chrome-stable_current_amd64.deb
  when: inst_chrome.chnaged

- name: Ensure package firefox is installed
  apt: pkg=firefox state=present