---
# Development configuration

- name: Installing Version Control Systems
  sudo: yes
  apt: pkg=git,mercurial state=installed

- name: Configuring GIT defaults
  template: src=common/templates/.gitconfig.j2 dest=/home/${username}/.gitconfig owner=$username group=$username mode=0644 backup=yes

- name: Installing system Ruby
  sudo: yes
  apt: pkg=ruby state=latest

- name: Checking Ruby RVM installation
  register: inst_rvm
  file: path=/home/${username}/.rvm state=directory

- name: Installing Ruby RVM
  shell: \curl -L https://get.rvm.io | bash -s stable
  when: inst_rvm.changed

- name: Checking Oracle JDK 7 installation
  sudo: yes
  register: inst_java
  file: path=/usr/lib/jvm/java-7-oracle state=directory

- name: Enabling Oracle JDK 7 PPA
  sudo: yes
  apt_repository: repo=ppa:webupd8team/java
  when: inst_java.changed

- name: Unattended installation
  sudo: yes
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- name: Installing Oracle JDK 7
  sudo: yes
  apt: pkg=oracle-java7-installer state=latest update_cache=yes
  when: inst_java.changed

- name: Installing Node Version Manager (NVM)
  register: inst_nvm
  git: repo=git://github.com/creationix/nvm.git dest=/home/${username}/.nvm
