---
# Some useful programs / tools

- name: Installing GIMP
  sudo: yes
  apt: pkg=gimp state=latest

- name: Installing Keepassx
  sudo: yes
  apt: pkg=keepassx state=latest

- name: Installing VLC
  sudo: yes
  apt: pkg=vlc state=latest

# POWER_UTILS
- name: Installing synaptic
  sudo: yes
  apt: pkg=synaptic state=latest

- name: Installing xChat
  sudo: yes
  apt: pkg=xchat state=latest


# TERMINAL_UTILS

- name: Install Terminal Utils:
  register: inst_term_utils
  action: apt pkg={{item}} state=installed
  with_items:
  - guake
  - nautilus-open-terminal
  - grsync

- name: Configure Terminal Utils
  command: {{ item }}
  with_items:
  - "gconftool -s /apps/guake/keybindings/global/show_hide --type=string 'F4'"
  - "gconftool -s /apps/guake/general/history_size --type=int 8192"
  - "gconftool -s /apps/guake/style/background/transparency --type=int 10"
  - "gconftool -s /apps/guake/general/window_ontop --type=bool false"
  - "gconftool -s /apps/guake/style/font/style --type=string 'Monospace 13'"
  when: inst_term_utils.changed


# GIT_POWER
- name: Install Git Utils:
  register: inst_git_utils
  action: apt pkg={{item}} state=installed
  with_items:
  - gitg
  - meld
  - git-gui
  - gitk
  - nautilus-compare


# Flash
- name: Installing browser flash plugin
  sudo: yes
  apt: pkg=flashplugin-installer state=latest

# HipChat
- name: Add hipchat repository into sources list.
  apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main' state=present

- name: add hipchat key
  sudo: yes
  apt_key: url=$hipchat_key_url state=present

- name: Installing xChat
  sudo: yes
  apt: pkg=hipchat state=installed